id: anet_c3d_msvg_dvc

visual_feature_type: c3d
visual_feature_folder: 'data/anet/features/c3d'
feature_dim: 500
invalid_video_json: []
train_caption_file: data/anet/captiondata/train_modified.json
train_proposal_file: data/generated_proposals/dbg_trainval_top100.json
eval_proposal_file: data/generated_proposals/dbg_trainval_top100.json
gt_file_for_eval: ['data/anet/captiondata/val_1.json', 'data/anet/captiondata/val_2.json']
gt_file_for_para_eval: ['data/anet/captiondata/para/anet_entities_val_1_para.json', 'data/anet/captiondata/para/anet_entities_val_2_para.json']
train_proposal_type: gt
gt_proposal_sample_num: 30
sample_method: nearest
dict_file: data/anet/vocabulary_activitynet_thres2.json
vocab_size: 8517

lr: 0.00005
learning_rate_decay_start: 8
learning_rate_decay_every: 3
learning_rate_decay_rate: 0.5
weight_decay: 0.0001
epoch: 25
eval_batch_size: 16
min_epoch_when_save: 2
train_use_amp: False
eval_use_amp: False
# model configs
num_queries: 30
ec_alpha: 1.0
save_dir: save


# grounding settings
eval_enable_grounding: True
eval_gt_file_for_grounding: data/anet/captiondata/grounding/val1_for_grounding.json

# Text encoder
word_context_modeling_type: attention_pool
text_encoder_learning_strategy: frozen
enable_layer_diff_text_feature: True
# Text Context Modeling
enable_word_context_modeling: True
enable_sentence_context_modeling: True
enable_sentence_pos_embedding: True
sentence_modeling_layer_num: 1
# contrastive loss
enable_contrastive: True
enable_cross_video_cl: True
cl_schedule_time: [0, 2]
cl_schedule_val: [0, 0.1]
contrastive_loss_temperature: 0.1
contrastive_hidden_size: 128
eval_set_cost_class: 0

dec_layers: 2
enc_layers: 2
transformer_ff_dim: 512
transformer_dropout_prob: 0.1
caption_decoder_type: standard
cap_nheads: 1
cap_dec_n_points: 4
cap_num_feature_levels: 4
soft_attention: 1
att_hid_size: 512
ec_alpha: 1.0


with_box_refine: 1
fix_xcw: 1
set_cost_caption: 0
set_cost_giou: 4
set_cost_bbox: 0
set_cost_class: 2
set_cost_cl: 2.0

caption_loss_coef: 2
giou_loss_coef: 4
bbox_loss_coef: 0
cls_loss_coef: 2
count_loss_coef: 0.5
max_eseq_length: 10
lloss_cross_entropy: 0
lloss_focal_loss: 0
lloss_gau_mask: 1